"""GitHub PR Automation Tool.

Orchestrates the full self-healing code workflow:
1. Run SAST scan on a repository
2. For each finding, invoke the DeveloperAgent to generate a patch
3. Create a branch, commit the fix, and open a Pull Request
"""

import logging
import hashlib
from typing import Dict, Any, List

from app.services.tools.base import BaseTool
from app.services.integrations.github_service import GitHubService
from app.services.agent.developer_agent import DeveloperAgent

logger = logging.getLogger("SageAI.github_pr_tool")


def _generate_branch_name(vuln_type: str, file_path: str) -> str:
    """Generate a unique, descriptive branch name for the fix."""
    slug = vuln_type.lower().replace(" ", "-").replace("_", "-")[:30]
    file_hash = hashlib.md5(file_path.encode()).hexdigest()[:6]
    return f"sageai-fix-{slug}-{file_hash}"


def _generate_pr_body(patch_result: Dict[str, Any]) -> str:
    """Generate a professional PR description with vulnerability details."""
    vuln = patch_result["vulnerability"]
    guardrails = patch_result["guardrail_result"]

    return f"""## 🛡️ SageAI Security Fix

### Vulnerability Detected
| Field | Value |
|-------|-------|
| **Type** | `{vuln['type']}` |
| **Severity** | `{vuln['severity']}` |
| **Test ID** | `{vuln['test_id']}` |
| **File** | `{patch_result['file_path']}` |
| **Line** | `{vuln['line']}` |

### Description
{vuln['issue_text']}

### Fix Applied
AI-generated secure patch that resolves the vulnerability while preserving business logic.

### Verification
- ✅ Guardrails passed ({guardrails['lines_changed']} lines changed)
- ✅ Post-patch SAST re-scan: **Clean**

### Security Impact
This fix prevents potential exploitation of the detected vulnerability.

---
*This Pull Request was automatically generated by [SageAI](https://github.com/sagarpritam/SageAI) — AI DevSecOps Platform.*

> ⚠️ **Always review AI-generated code before merging.**

Labels: `security`, `sageai-fix`
"""


class GitHubPRTool(BaseTool):
    """
    Orchestrates the entire self-healing code workflow:
    Takes SAST findings, generates AI patches, and opens GitHub PRs.
    """

    @property
    def name(self) -> str:
        return "github_autofix"

    @property
    def description(self) -> str:
        return (
            "Automatically fixes security vulnerabilities found by SAST scanning. "
            "Generates AI-powered code patches and opens GitHub Pull Requests with the fixes."
        )

    async def run(self, target: str, **kwargs) -> Dict[str, Any]:
        """
        Run the auto-fix workflow.
        
        Args:
            target: GitHub repo in 'owner/repo' format
            **kwargs:
                github_token: Decrypted GitHub PAT (required)
                findings: List of SAST findings to fix
                branch: Base branch (default: 'main')
                org_id: Organization ID for token tracking
        """
        github_token = kwargs.get("github_token", "")
        findings: List[Dict] = kwargs.get("findings", [])
        base_branch = kwargs.get("branch", "main")
        org_id = kwargs.get("org_id", "system")

        if not github_token:
            return {"error": "GitHub token is required for auto-fix."}
        if not findings:
            return {"error": "No findings to fix."}

        parts = target.strip("/").split("/")
        if len(parts) != 2:
            return {"error": f"Invalid repo format. Expected 'owner/repo', got '{target}'"}
        owner, repo = parts

        github = GitHubService(github_token)
        agent = DeveloperAgent(github, org_id=org_id)

        results = {
            "repository": target,
            "total_findings": len(findings),
            "fixed": [],
            "failed": [],
            "blocked": [],
            "pull_requests": []
        }

        for finding in findings:
            file_path = finding.get("file", "unknown")
            vuln_type = finding.get("test_name", "unknown")

            logger.info(f"Processing: {vuln_type} in {file_path}")

            # 1. Generate the AI patch
            patch_result = await agent.generate_patch(owner, repo, finding, branch=base_branch)

            if patch_result is None:
                results["failed"].append({
                    "file": file_path,
                    "vulnerability": vuln_type,
                    "reason": "AI could not generate a valid patch after retries."
                })
                continue

            if not patch_result["guardrail_result"]["approved"]:
                results["blocked"].append({
                    "file": file_path,
                    "vulnerability": vuln_type,
                    "reasons": patch_result["guardrail_result"]["reasons"]
                })
                continue

            # 2. Create a branch for the fix
            branch_name = _generate_branch_name(vuln_type, file_path)
            try:
                await github.create_branch(owner, repo, base_branch, branch_name)
            except Exception as e:
                logger.error(f"Failed to create branch {branch_name}: {e}")
                results["failed"].append({
                    "file": file_path,
                    "vulnerability": vuln_type,
                    "reason": f"Branch creation failed: {str(e)}"
                })
                continue

            # 3. Commit the patched file
            commit_message = f"fix: resolve {vuln_type} in {file_path}\n\nAuto-fixed by SageAI Developer Agent."
            try:
                commit_url = await github.commit_file(
                    owner, repo, branch_name,
                    file_path, patch_result["patched_code"],
                    commit_message
                )
            except Exception as e:
                logger.error(f"Failed to commit patch: {e}")
                results["failed"].append({
                    "file": file_path,
                    "vulnerability": vuln_type,
                    "reason": f"Commit failed: {str(e)}"
                })
                continue

            # 4. Open a Pull Request
            pr_title = f"🛡️ Fix: {vuln_type} in {file_path}"
            pr_body = _generate_pr_body(patch_result)
            try:
                pr_url = await github.create_pull_request(
                    owner, repo, branch_name, base_branch,
                    pr_title, pr_body
                )
                results["pull_requests"].append(pr_url)
                results["fixed"].append({
                    "file": file_path,
                    "vulnerability": vuln_type,
                    "pr_url": pr_url,
                    "lines_changed": patch_result["guardrail_result"]["lines_changed"]
                })
                logger.info(f"✅ PR created: {pr_url}")
            except Exception as e:
                logger.error(f"Failed to create PR: {e}")
                results["failed"].append({
                    "file": file_path,
                    "vulnerability": vuln_type,
                    "reason": f"PR creation failed: {str(e)}"
                })

        # Summary
        results["summary"] = (
            f"Processed {len(findings)} findings: "
            f"{len(results['fixed'])} fixed, "
            f"{len(results['failed'])} failed, "
            f"{len(results['blocked'])} blocked by guardrails."
        )
        logger.info(results["summary"])

        return results
